---
title: "houses"
author: "David Puelz"
date: "9/27/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




## R Markdown

<!-- ```{r} -->
<!-- data = read.csv('PricesSales.csv') -->
<!-- fit = lm(Sales~p1+p2,data) -->
<!-- summary(fit) -->
<!-- ``` -->

# ```{r}
# data = read.csv('nbeer.csv')
# fit = lm(nbeer~weight,data)
# summary(fit)
# ```

# ```{r}
# data = read.table("SalaryData.txt",header=T)
# Sex = (data$Gender=="Male")
# data$Sex = Sex
# fit = lm(Salary~Sex,data)
# coef(fit)[2] # regression coefficient
#
# DiM = mean(data$Salary[Sex==1]) - mean(data$Salary[Sex==0])
# DiM # what is this?
# ```
```{r}
data = read.table("SalaryData.txt",header=T)
Sex = (data$Gender=="Male")
data$Sex = Sex
Exp = 95-data$YrHired
data$Exp = Exp
data$ExpSex = Exp*Sex 
fit = lm(Salary~Sex+Exp+ExpSex,data)
summary(fit)
```


```{r}
# data = read.csv("MidCity.csv")
# 
# data$Price = data$Price/1000
# data$SqFt = data$SqFt/1000
# dn1 = as.integer(data$Nbhd==1)
# dn2 = as.integer(data$Nbhd==2)
# dn3 = as.integer(data$Nbhd==3)
# data$dn1 = dn1
# data$dn2 = dn2
# data$dn3 = dn3
# 
# fit = lm(Price~SqFt,data)
# summary(fit)
```
