---
title: "Units, Dimension, and Scale"
author: "Professors David Ruth and David Puelz"
institute: "The University of Austin"
output:
  beamer_presentation:
    theme: "default"
    latex_engine: "xelatex"
    keep_tex: true
header-includes:
  - \definecolor{burntorange}{rgb}{0.968, 0.549, 0.114}
  - \definecolor{burntorangedark}{rgb}{0.486, 0.306, 0.102}
  - \definecolor{lightblue}{rgb}{0.161, 0.471, 1}
  - \definecolor{lightbluedark}{rgb}{0.125, 0.271, 0.510}
  - \definecolor{charcoal}{rgb}{0.21, 0.27, 0.31}
  - \definecolor{darkgray}{rgb}{0.3, 0.3, 0.3}
  - \definecolor{darkgrey}{rgb}{0.33, 0.33, 0.33}
  - \definecolor{cadmiumgreen}{rgb}{0.0, 0.42, 0.24}
  - \definecolor{brandeisblue}{rgb}{0.0, 0.44, 1.0}
  - \setbeamercolor{structure}{fg=darkgray}
  - \setbeamercolor{footline}{fg=darkgray}
  - \usepackage{amssymb, bm}
  - \usepackage{amsmath, amsfonts, amscd, epsfig, amssymb, amsthm, adjustbox}
  - \usepackage{textcomp}
  - \usepackage{graphicx}
  - \usepackage{setspace}
  - \usepackage{enumitem}
  - \setlist[itemize]{itemsep=9pt, label={--}}
  - \usepackage{anyfontsize}
  - \usepackage{ulem}
  - \usepackage{tcolorbox}[most]
  - \usepackage{tikz}
  - \usepackage[T1]{fontenc}
  - \usepackage{booktabs}
  - \usepackage{soul}
  - \setul{4.5pt}{3pt} % First value is thickness, second is distance from text
  - \usepackage{colortbl}
  - \usepackage{multirow}
  - \usepackage{array}
  - \usepackage{longtable}
  - \usepackage{listings}
  - \usepackage{color}
  - \usepackage{bbold}
  - \usepackage{mathtools}
  - \newcolumntype{K}[1]{>{\centering\arraybackslash}p{#1}}
  - \newcolumntype{Q}[1]{>{\columncolor[gray]{0.8}\centering\arraybackslash}p{#1}}
  - \newcommand\eho{\stackrel{\mathclap{\small\mbox{$H_0$}}}{=}}
  - \newcommand\norm[1]{\left\lVert#1\right\rVert}
  - \newcommand\smalldp{\fontsize{9.4}{7.2}\selectfont}
  - \newcommand\smalldpp{\fontsize{8.5}{7.2}\selectfont}
  - \newcommand\smalldppgh{\fontsize{9.5}{7.2}\selectfont}
  - \newcolumntype{H}{>{\setbox0=\hbox\bgroup}c<{\egroup}@{}}
  - \newcommand{\bo}[1]{\textcolor{burntorange}{#1}}
  - \newcommand{\bod}[1]{\textcolor{burntorangedark}{#1}}
  - \newcommand{\lb}[1]{\textcolor{lightblue}{#1}}
  - \newcommand{\lbd}[1]{\textcolor{lightbluedark}{#1}}
  - \newcommand{\dg}[1]{\textcolor{darkgray}{#1}}
  - \newcommand{\bi}{\begin{itemize}}
  - \newcommand{\ib}{\end{itemize}}
  - \newcommand{\p}{\item}
  - \newcommand{\sk}{\vspace{.5cm}}
  - \newcommand{\sko}{\vspace{.1in}}
  - \newcommand{\skoo}{\vspace{.2in}}
  - \newcommand{\skooo}{\vspace{.3in}}
  - \newcommand{\skoooo}{\vspace{.05in}}
  - \newcommand{\hko}{\hspace{.1in}}
  - \newcommand{\hkoo}{\hspace{.2in}}
  - \newcommand{\hkooo}{\hspace{.3in}}
  - \newcommand{\bb}{$\lb{{\small \bullet } }$ \hspace{0.5mm}}
  - \newcommand{\ba}{$\lb{{\small \rightarrow } }$ \hspace{0.5mm}}
  - \setbeamertemplate{footline}{\scriptsize{\hfill\insertframenumber\vspace{-.2cm}\hspace*{.35cm}}} 
  - \usepackage{xcolor}
  - \definecolor{myorange}{RGB}{255, 94, 77}
  - \setbeamertemplate{footline}{}
  - \usepackage{ragged2e}
---

# Units, Dimension, and Scale 
Goals:

-   Review notions of unit, dimension, and scale

-   Explore arsenic case study

-   Program in Python

# Zaslow Appendix 5 (review/learn)

-   5.1: Units

-   5.2: Scientific notation

-   5.3: Scientific notation under operations

# Some practical instances (estimate value with appropriate unit) 

-   US Gross Domestic Product

-   Avagadro's number

-   number of calculations a supercomputer performs in a day

-   chance of winning this week's Powerball jackpot

-   charge on an electron

-   number of cells in a liver

# Intensive vs. extensive properties

The physical properties of a system can be classified into two categories:

-   __Extensive properties__ depend on the mass of a system.

-   __Intensive properties__ are independent of the mass of a system.

Examples of each?

\pause
See https://sciencenotes.org/intensive-extensive-properties/ for more on this.

# Zaslow Ch. 4 - Should I worry about arsenic (As) in rice?
\pause
Do you you have a prior opinion?

\pause
What are the possible responses?

\pause
What would it take for you to favor a particular respone?

\pause
What are the key subquestions to answer?

\pause
-   How much As do I ingest associated with rice consumption?

\pause
-   Is that quantity of As enough to worry about?

# Example: ppm 
Quantities of As in water are are measured in _parts per million_, or _ppm_.
\pause

\begin{center}
ppm = (mass of solute)/(mass of solution)
\end{center}

\pause
Note: "ppm" is technically unitless; i.e.,

\begin{center}
1 ppm = 1 mg/kg
\end{center}

\pause
For water solution with neglible solute mass,

\begin{center}
ppm = 1 mg/L
\end{center}

# Zaslow Ch. 4 - Should I worry about arsenic (As) in rice?

\centering
\LARGE  SHIFT TO WHITEBOARD


# Python programming
Two programs today:

- Simple program that triples and input and generates formatted output.

- Documented program that performs conversion similar to assigned problem.

